#!/bin/bash

for f in *
	do
	if [ "$f" != "quickpush" ]
		then
		git add $f
	fi
done

for f in .*
	do 
	if [ "$f" != ".." ]
		then
		git add -f $f
	fi
done

if [ "$1" = "" ]
	then
		git commit -m "QuickPush by http://github.com/sjradach"
	else
		git commit -m "$1"
fi
git push
